version: "3.3"
services:
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "kholids"
      # You can use whatever password you like
      MYSQL_PASSWORD: "kholids"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    # volumes:
    #   - D:\Refactory\Project\public_html\web-server\Databases\mysql
      # - /home/emanuel/Databases/mysql:/var/lib/mysql
      # - $PWD/mysql.conf:/etc/mysql/conf.d/mysql.cnf
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
    environment:
      - ADMINER_DESIGN='nette'
  pma:
    image: phpmyadmin
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1